name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.x"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build
        run: go build -race -v -o ./demo.app ./demo

      - name: Test
        run: make test

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          version: v1.62.2
          skip-cache: true
